"""
===========================================================
VisionRestore AI
Phase 3 : Restoration Engine
Part 1 : Pipeline Skeleton
===========================================================

This module is responsible for executing the restoration
pipeline generated by the Quality Analyzer.

(Current Version)
-----------------
✔ Image Loading
✔ Restoration Pipeline Execution
✔ Placeholder Restoration Functions
✔ Image Saving
✔ Visualization
"""
from pathlib import Path

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ==========================================================
# RESTORATION MODULES
# ==========================================================

from restoration.dncnn import DnCNNRestorer
from restoration.swinir import SwinIRRestorer
from restoration.contrast import enhance_contrast
from restoration.low_light import enhance_low_light
from restoration.median_filter import remove_salt_pepper
# ==========================================================
# CONFIGURATION
# ==========================================================

OUTPUT_DIR = Path("outputs/restored")

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ==========================================================
# LOAD RESTORATION MODELS
# ==========================================================

dncnn_restorer = DnCNNRestorer()

swinir_restorer = SwinIRRestorer()
# ==========================================================
# IMAGE LOADER
# ==========================================================

def load_image(image_path):

    image = cv2.imread(str(image_path))

    if image is None:
        raise FileNotFoundError(
            f"Unable to load {image_path}"
        )

    image = cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )

    return image


# ==========================================================
# IMAGE SAVER
# ==========================================================

def save_image(image, filename):

    output_path = OUTPUT_DIR / filename

    image = cv2.cvtColor(
        image,
        cv2.COLOR_RGB2BGR
    )

    cv2.imwrite(
        str(output_path),
        image
    )

    print(f"\n[OK] Restored image saved at\n{output_path}")

    return output_path


# ==========================================================
# PLACEHOLDER RESTORATION FUNCTIONS
# ==========================================================

def deblur(image):

    print("Executing SwinIR Enhancement...")

    restored, _ = swinir_restorer.upscale(image)

    return restored

# ----------------------------------------------------------


def denoise(image):

    print("Executing DnCNN...")

    noise_score = 20

    restored, _, _ = dncnn_restorer.restore(
        image,
        noise_score
    )

    return restored

# ----------------------------------------------------------


def low_light_enhancement(image):

    print("Executing Gamma + CLAHE...")

    return enhance_low_light(image)


# ----------------------------------------------------------

def contrast_enhancement(image):

    print("Executing CLAHE...")

    return enhance_contrast(image)
def salt_pepper_removal(image):

    print("Executing Median Filter...")

    return remove_salt_pepper(image)

def super_resolution(image):

    print("Executing SwinIR Super Resolution...")

    restored, _ = swinir_restorer.upscale(image)

    return restored




# ==========================================================
# OPERATION REGISTRY
# ==========================================================
RESTORATION_FUNCTIONS = {

    "Deblur": deblur,

    "Denoise": denoise,

    "Low-Light Enhancement": low_light_enhancement,

    "Contrast Enhancement": contrast_enhancement,

    "Salt & Pepper Removal": salt_pepper_removal,

    "Super Resolution": super_resolution

}

# ==========================================================
# PIPELINE EXECUTOR
# ==========================================================

def execute_pipeline(image, recommendation):

    restored = image.copy()

    print("\n")

    print("=" * 60)
    print("RESTORATION PIPELINE")
    print("=" * 60)

    for step in recommendation["recommended_pipeline"]:

        operation = step["operation"]

        model = step["model"]

        print(
            f"\n→ {operation} ({model})"
        )

        function = RESTORATION_FUNCTIONS.get(operation)

        if function is None:

            print(
                f"Skipping {operation}"
            )

            continue

        restored = function(restored)

    print("\nPipeline Completed.")

    return restored


# ==========================================================
# VISUALIZATION
# ==========================================================

def visualize(original,
              restored):

    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)

    plt.imshow(original)

    plt.title("Original")

    plt.axis("off")

    plt.subplot(1, 2, 2)

    plt.imshow(restored)

    plt.title("Restored")

    plt.axis("off")

    plt.tight_layout()

    plt.show()


# ==========================================================
# MAIN EXECUTION FUNCTION
# ==========================================================

def restore_image(
        image_path,
        recommendation):

    image = load_image(
        image_path
    )

    restored = execute_pipeline(
        image,
        recommendation
    )

    save_image(
        restored,
        Path(image_path).name
    )

    visualize(
        image,
        restored
    )

    return restored


# ==========================================================
# MAIN
# ==========================================================
# ==========================================================
# MAIN
# ==========================================================

def main():

    sample_image = Path(
        r"D:/PLACEMENT/HYPERVERGE/PIXEL_RESTORE/data/processed/gaussian_noise/00040534.png"
    )

    recommendation = {

        "recommended_pipeline": [

            {
                "step": 1,
                "operation": "Denoise",
                "model": "DnCNN"
            },

            {
                "step": 2,
                "operation": "Contrast Enhancement",
                "model": "CLAHE"
            }

        ]

    }

    restore_image(
        sample_image,
        recommendation
    )


if __name__ == "__main__":

    main()