"""
===========================================================
VisionRestore AI
Phase 3 : Restoration Engine
===========================================================

Executes the restoration pipeline generated by
quality_analyzer.py.

Supports

• DnCNN
• Median Filter
• CLAHE
• Gamma Correction
• SwinIR
===========================================================
"""

from pathlib import Path

import cv2
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# Import Restoration Modules
# ---------------------------------------------------------

# from restoration.dncnn import DnCNNRestorer

from restoration.contrast import enhance_contrast

from restoration.low_light import enhance_low_light

from restoration.median_filter import median_denoise

# from restoration.swinir import SwinIRRestorer


# ==========================================================
# OUTPUT DIRECTORY
# ==========================================================

OUTPUT_DIR = Path("outputs/restored")

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ==========================================================
# LOAD IMAGE
# ==========================================================

def load_image(image_path):

    image = cv2.imread(str(image_path))

    if image is None:

        raise FileNotFoundError(image_path)

    return cv2.cvtColor(
        image,
        cv2.COLOR_BGR2RGB
    )


# ==========================================================
# SAVE IMAGE
# ==========================================================

def save_image(image, filename):

    output_path = OUTPUT_DIR / filename

    cv2.imwrite(

        str(output_path),

        cv2.cvtColor(
            image,
            cv2.COLOR_RGB2BGR
        )

    )

    return output_path


# ==========================================================
# RESTORATION EXECUTOR
# ==========================================================

def execute_pipeline(image, recommendation, report):

    restored = image.copy()

    print("\n")
    print("=" * 60)
    print("RESTORATION PIPELINE")
    print("=" * 60)

    dncnn = None
    swinir = None

    for step in recommendation["recommended_pipeline"]:

        operation = step["operation"]

        model = step["model"]

        print(f"\n{operation}")
        print(f"Model : {model}")

        # --------------------------------------------------
        # DnCNN
        # --------------------------------------------------

        if model == "DnCNN":

            if dncnn is None:
                from restoration.dncnn import DnCNNRestorer

                dncnn = DnCNNRestorer()

            restored, _, _ = dncnn.restore(
                restored,
                noise_score=report["Noise Score"]
            )

        # --------------------------------------------------
        # Median Filter
        # --------------------------------------------------

        elif model == "Median Filter":

            restored = median_denoise(restored)

        # --------------------------------------------------
        # CLAHE
        # --------------------------------------------------

        elif model == "CLAHE":

            restored = enhance_contrast(restored)

        # --------------------------------------------------
        # Gamma Correction
        # --------------------------------------------------

        elif model == "Gamma Correction":

            restored = enhance_low_light(restored)

        # --------------------------------------------------
        # SwinIR
        # --------------------------------------------------

        elif model == "SwinIR":

            if swinir is None:
                from restoration.swinir import SwinIRRestorer

                swinir = SwinIRRestorer()

            restored, _ = swinir.upscale(restored)

        # --------------------------------------------------
        # Joint Restoration
        # --------------------------------------------------

        elif operation == "Joint Restoration":

            if dncnn is None:

                dncnn = DnCNNRestorer()

            restored, _, _ = dncnn.restore(
                restored,
                noise_score=20
            )

            if swinir is None:

                swinir = SwinIRRestorer()

            restored, _ = swinir.upscale(restored)

    print("\n✓ Restoration Completed")

    return restored


# ==========================================================
# VISUALIZATION
# ==========================================================

def visualize(original, restored):

    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)

    plt.imshow(original)

    plt.title("Original")

    plt.axis("off")

    plt.subplot(1,2,2)

    plt.imshow(restored)

    plt.title("Restored")

    plt.axis("off")

    plt.tight_layout()

    plt.show()


# ==========================================================
# COMPLETE RESTORATION
# ==========================================================

def restore_image(
    image_path,
    recommendation,
    report
):

    image = load_image(image_path)

    restored = execute_pipeline(
        image,
        recommendation,
        report
    )
    output = save_image(
        restored,
        Path(image_path).name
    )

    visualize(
        image,
        restored
    )

    print("\nSaved :", output)

    return restored


# ==========================================================
# DEMO
# ==========================================================

def main():

    image_path = Path(
        r"data/processed/gaussian_noise/00040534.png"
    )

    recommendation = {

        "recommended_pipeline":[

            {
                "step":1,
                "operation":"Denoise",
                "model":"DnCNN"
            },

            {
                "step":2,
                "operation":"Contrast Enhancement",
                "model":"CLAHE"
            }

        ]

    }

    restore_image(
        image_path,
        recommendation
    )


if __name__ == "__main__":

    main()